import NavBar from "@/components/main_components/nav_bar";
import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster";
import BackToTop from "@/components/main_components/back_to_top";
import Footer from "@/components/main_components/footer";

export const metadata: Metadata = {
  title: "Fayida Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Toaster />
        
        {/* Header */}
        <header className="w-full">
          <NavBar />
        </header>
        
        {/* Main content */}
        <main className="flex-grow pt-8 xmd:pt-20 w-full">
          {children}
        </main>
        
        {/* Back to top button */}
        <div className="fixed bottom-14 right-8 z-50">
          <BackToTop />
        </div>
        
        {/* Footer */}
        <footer className="w-full">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
