import NavBar from "@/components/main_components/nav_bar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Fayida Acadamy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <div className="absolute top-0 w-full">
          <div className="">
            <NavBar />
          </div>
          <div className="pt-8 xmd:pt-16">{children}</div>
        </div>
      </body>
    </html>
  );
}
